### PR TITLE
PassThroughPlayer options extended by audioTransformer option

### PR DESCRIPTION
**Pull request by davidslaby**
`audioTransformer` option allows you to pass a transformation function as parameter.
It's usable to filter audio channels frame by frame, etc.

### CODE REVIEW

**Comment by davidslaby** [comment]
@monyone I want to kindly ask you, could you check this PR, please? And in case you like the solution, publish new version of package? Thanks in advance. :)

**Comment by monyone** [comment]
It's seems ok. thank you!

**Comment by davidslaby** [comment]
@monyone Could you merge this PR and publish new version of package, please? Thank you!

**Comment by monyone** [comment]
sorry for late, Merged and Published!

**Pull request merged**
