### PR TITLE
fetch options support

### PR DESCRIPTION
**Pull request by davidslaby**
As we are going to authenticate a user, we need to support passing options in request - fetch. It's done within this PR.

### CODE REVIEW

**Comment by davidslaby** [comment]
@monyone Could you check, please? And eventually publish new version? Thanks in advance!

**Comment by monyone** [comment]
It's seems to no way to pass fetchOptions by Player in this PR.
I'll fix constructor for passing fetchOptions.

**Comment by davidslaby** [comment]
I think, you can pass it as parameter of load, which we use to fetch the stream.

**Comment by davidslaby** [comment]
```

zlplayer.load(url, fetchOptions).then(() => {
   videoElement.play()
})

```

**Comment by monyone** [comment]
late for bumpup npm. sorry

**Pull request merged**
